// Generated by CoffeeScript 1.7.1
(function() {
  var Task, TaskListViewModel;

  Task = (function() {
    function Task(title) {
      this.title = title;
      this.isDone = ko.observable(false);
    }

    return Task;

  })();

  TaskListViewModel = (function() {
    function TaskListViewModel() {
      this.tasks = ko.observableArray([]);
      this.newTaskText = ko.observable();
      this.incompleteTasks = ko.computed((function(_this) {
        return function() {
          return ko.utils.arrayFilter(_this.tasks(), function(task) {
            return !task.isDone();
          });
        };
      })(this));
      this.addTask = function() {
        this.tasks.push(new Task(this.newTaskText()));
        return this.newTaskText("");
      };
      this.removeTask = (function(_this) {
        return function(task) {
          return _this.tasks.remove(task);
        };
      })(this);
    }

    return TaskListViewModel;

  })();

  ko.applyBindings(new TaskListViewModel());

}).call(this);
